#!/bin/sh
# TP-Link Archer AX55 v1 test image - bring the Wi-Fi up as a WPA2 AP.
#
# This runs from the ieee80211 hotplug (ACTION=add) which fires when ath11k
# finishes loading its firmware and registers each PHY (~14s into boot) - i.e.
# AFTER 10-wifi-detect has run "wifi config" to generate /etc/config/wireless.
# Doing this from a uci-defaults script instead would run too early (~10s),
# before the radios exist, and leave the Wi-Fi unconfigured.

[ "${ACTION}" = "add" ] || exit 0
[ -f /etc/config/wireless ] || exit 0

WIFI_SSID="OpenWrt-AX55"
WIFI_KEY="ax55test"
WIFI_COUNTRY="PL"

. /lib/functions.sh
config_load wireless

enable_device() {
	uci -q set wireless."$1".disabled='0'
	uci -q set wireless."$1".country="$WIFI_COUNTRY"
}

setup_iface() {
	uci -q set wireless."$1".disabled='0'
	uci -q set wireless."$1".mode='ap'
	uci -q set wireless."$1".network='lan'
	uci -q set wireless."$1".encryption='psk2'
	uci -q set wireless."$1".key="$WIFI_KEY"
	uci -q set wireless."$1".ssid="$WIFI_SSID"
}

config_foreach enable_device wifi-device
config_foreach setup_iface wifi-iface
uci -q commit wireless

wifi up
